name: Run Pytest

on: [push]

permissions:
  pull-requests: write

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
                  cache: "pip"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pytest pytest-cov
                  pip install .

            - name: Run tests and generate coverage report
              run: |
                    python -m pytest tests/ -cov=./ --cov-report=term-missing:skip-covered \
                    --junitxml=pytest.xml | tee pytest-coverage.txt

            - name: Post Pytest Coverage Comment
              uses: MishaKav/pytest-coverage-comment@v1
              with:
                pytest-coverage-path: ./pytest-coverage.txt
                junitxml-path: ./pytest.xml
